global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['ouroapp:3000']
  - job_name: 'mongo'
    static_configs:
      - targets: ['ouromongo:27017']